FROM python:3.11-bullseye


ENV PYTHONUNBUFFERED=1


WORKDIR /instagram_app


COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt


COPY . .


CMD echo "Apply database migrations" && python manage.py migrate && \
    echo "Starting server" && python manage.py runserver 0.0.0.0:8000
